; Shared sound command defines

SOUNDCMD_PlayJingleA	= $02
SOUNDCMD_PlayCoinA		= $20
SOUNDCMD_PlayLeft  		= $21
SOUNDCMD_PlayRight		= $22
SOUNDCMD_PlayCenter 	= $23
SOUNDCMD_StopA			= $30
SOUNDCMD_PlayB			= $31
SOUNDCMD_StopB			= $32

SOUNDCMD_SSGRampinit	= $40
SOUNDCMD_SSGRampcycle	= $41
SOUNDCMD_SSGPulseStart	= $42
SOUNDCMD_SSGPulseStop	= $43

SOUNDCMD_RateB_0		= $80
SOUNDCMD_RateB_1		= $81
SOUNDCMD_RateB_2		= $82
SOUNDCMD_RateB_3		= $83
SOUNDCMD_RateB_4		= $84
SOUNDCMD_RateB_5		= $85
SOUNDCMD_RateB_6		= $86
SOUNDCMD_RateB_7		= $87

