; Shared sound command defines

SOUNDCMD_PlayJingleA	= $02
SOUNDCMD_PlayCoinA		= $20
SOUNDCMD_PlayLeft  		= $21
SOUNDCMD_PlayRight		= $22
SOUNDCMD_PlayCenter 	= $23
SOUNDCMD_StopADPCMA		= $30
SOUNDCMD_ADPCMB_Left	= $31
SOUNDCMD_ADPCMB_Center	= $32
SOUNDCMD_ADPCMB_Right	= $33
SOUNDCMD_StopADPCMB		= $34
SOUNDCMD_LoopB			= $35
SOUNDCMD_NoLoopB		= $36

SOUNDCMD_SSGRampinit	= $40
SOUNDCMD_SSGRampcycle	= $41
SOUNDCMD_SSGPulseStart	= $42
SOUNDCMD_SSGPulseStop	= $43

SOUNDCMD_RateB_0		= $80
SOUNDCMD_RateB_1		= $81
SOUNDCMD_RateB_2		= $82
SOUNDCMD_RateB_3		= $83
SOUNDCMD_RateB_4		= $84
SOUNDCMD_RateB_5		= $85
SOUNDCMD_RateB_6		= $86
SOUNDCMD_RateB_7		= $87

