/* PCe CD Data Paker Offset for File gdata.bin */

#define	OFS_back512_BAT_bin	0
#define	SIZE_back512_BAT_bin	3840
#define	OFS_back512_DATA_bin	2
#define	SIZE_back512_DATA_bin	4448
#define	OFS_back512_PAL_bin	5
#define	SIZE_back512_PAL_bin	32
#define	OFS_color_BAT_bin	6
#define	SIZE_color_BAT_bin	2400
#define	OFS_color_DATA_bin	8
#define	SIZE_color_DATA_bin	2208
#define	OFS_color_PAL_bin	10
#define	SIZE_color_PAL_bin	512
#define	OFS_lagspr_tile_bin	11
#define	SIZE_lagspr_tile_bin	512
#define	OFS_LEDsprites_tile_bin	12
#define	SIZE_LEDsprites_tile_bin	512
#define	OFS_mainbg_BAT_bin	13
#define	SIZE_mainbg_BAT_bin	4096
#define	OFS_mainbg_DATA_bin	15
#define	SIZE_mainbg_DATA_bin	4256
#define	OFS_mainbg_PAL_bin	18
#define	SIZE_mainbg_PAL_bin	32
#define	OFS_motoko_BAT_bin	19
#define	SIZE_motoko_BAT_bin	2400
#define	OFS_motoko_DATA_bin	21
#define	SIZE_motoko_DATA_bin	21792
#define	OFS_motoko_PAL_bin	32
#define	SIZE_motoko_PAL_bin	512
#define	OFS_N_BAT_bin	33
#define	SIZE_N_BAT_bin	1472
#define	OFS_N_DATA_bin	34
#define	SIZE_N_DATA_bin	22560
#define	OFS_N_PAL_bin	46
#define	SIZE_N_PAL_bin	512
#define	OFS_numbers_tile_bin	47
#define	SIZE_numbers_tile_bin	5632
#define	OFS_SD_tile_bin	50
#define	SIZE_SD_tile_bin	3584
#define	OFS_shadow_tile_bin	52
#define	SIZE_shadow_tile_bin	512
#define	OFS_sonic_BAT_bin	53
#define	SIZE_sonic_BAT_bin	2400
#define	OFS_sonic_DATA_bin	55
#define	SIZE_sonic_DATA_bin	10624
#define	OFS_sonic_PAL_bin	61
#define	SIZE_sonic_PAL_bin	512
#define	OFS_sonicpalm_tile_bin	62
#define	SIZE_sonicpalm_tile_bin	4480
#define	OFS_striped_tile_bin	65
#define	SIZE_striped_tile_bin	512
