name: BUILD-NINTENDO_GAMECUBE-ROM

on:
  push:
    paths:
    - '.github/workflows/build-gamecube-rom.yml'
    - '240psuite/Wii/**'
  pull_request:
    paths:
    - '.github/workflows/build-gamecube-rom.yml'
    - '240psuite/Wii/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build tools
      run: |
        sudo apt-get install zlib1g-dev
        whereis gcc
        cd ./240psuite/Wii/240pSuite/tools
        # build cfile binary (linux specific) and ensure it is at this path.
        gcc cfile.c -lz -o cfile

    - name: Build ROM
      uses: docker://devkitpro/devkitppc:latest
      run: |
        whereis gcc
        sudo dkp-pacman -Syu gamecube-dev --noconfirm --needed
        cd ./240psuite/Wii/240pSuite
        make -f Makefile.gc

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_GAMECUBE-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/Wii/*.dol
