; Shared sound command defines

SOUNDCMD_PlayJingleA    = $02
SOUNDCMD_StopAll        = $04
RAMTESTCMD              = $10

SOUNDCMD_PlayCoinA      = $20
SOUNDCMD_PlayLeft       = $21
SOUNDCMD_PlayRight      = $22
SOUNDCMD_PlayCenter     = $23
SOUNDCMD_PlaySweep      = $24
SOUNDCMD_StopADPCMA     = $2f

SOUNDCMD_ADPCMB_Left    = $30
SOUNDCMD_ADPCMB_Center  = $31
SOUNDCMD_ADPCMB_Right   = $32
SOUNDCMD_LoopB          = $33
SOUNDCMD_NoLoopB        = $34
SOUNDCMD_ADPCMB_Sample0 = $35
SOUNDCMD_ADPCMB_LdSweep = $36
SOUNDCMD_StopADPCMB     = $3f

SOUNDCMD_RateB_0        = $40
SOUNDCMD_RateB_1        = $41
SOUNDCMD_RateB_2        = $42
SOUNDCMD_RateB_3        = $43
SOUNDCMD_RateB_4        = $44
SOUNDCMD_RateB_5        = $45
SOUNDCMD_RateB_6        = $46
SOUNDCMD_RateB_7        = $47

SOUNDCMD_RateB_0_Play   = $48
SOUNDCMD_RateB_1_Play   = $49
SOUNDCMD_RateB_2_Play   = $4A
SOUNDCMD_RateB_3_Play   = $4B
SOUNDCMD_RateB_4_Play   = $4C
SOUNDCMD_RateB_5_Play   = $4D
SOUNDCMD_RateB_6_Play   = $4E
SOUNDCMD_RateB_7_Play   = $4F

SOUNDCMD_SSGRampinit    = $50
SOUNDCMD_SSGRampcycle   = $51
SOUNDCMD_SSGRampStep    = $52
SOUNDCMD_SSGPulseStart  = $53
SOUNDCMD_SSGPulseStop   = $54
SOUNDCMD_SSG1KHZStart   = $55
SOUNDCMD_SSG1KHZStop    = $56
SOUNDCMD_SSG260HZStart  = $57
SOUNDCMD_SSG260HZStop   = $58
SOUNDCMD_SSGNoiseStart  = $59
SOUNDCMD_SSGNoiseStop   = $5a
SOUNDCMD_SSGNoiseRamp   = $5b
SOUNDCMD_SSGStop        = $5f

SOUNDCMD_FMInitSndTest  = $60
SOUNDCMD_FMPlay         = $61
SOUNDCMD_FMUseLeft      = $62
SOUNDCMD_FMUseCenter    = $63
SOUNDCMD_FMUseRight     = $64
SOUNDCMD_FMInitMDF      = $65
SOUNDCMD_FMNextMDF      = $66
SOUNDCMD_FMStopAll      = $6f

SOUNDCMD_FMOctave0      = $70
SOUNDCMD_FMOctave1      = $71
SOUNDCMD_FMOctave2      = $72
SOUNDCMD_FMOctave3      = $73
SOUNDCMD_FMOctave4      = $74
SOUNDCMD_FMOctave5      = $75
SOUNDCMD_FMOctave6      = $76
SOUNDCMD_FMOctave7      = $77

SOUNDCMD_FMNote0        = $80
SOUNDCMD_FMNote1        = $81
SOUNDCMD_FMNote2        = $82
SOUNDCMD_FMNote3        = $83
SOUNDCMD_FMNote4        = $84
SOUNDCMD_FMNote5        = $85
SOUNDCMD_FMNote6        = $86
SOUNDCMD_FMNote7        = $87
SOUNDCMD_FMNote8        = $88
SOUNDCMD_FMNote9        = $89
SOUNDCMD_FMNote10       = $8A
SOUNDCMD_FMNote11       = $8B
SOUNDCMD_FMNote12       = $8C

SOUNDCMD_CheckVersion   = $D0


